# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
from ccxt import bybit
from ccxtpro.base.exchange import Exchange
import ccxt.async_support as ccxt
from ccxtpro.base.cache import ArrayCache, ArrayCacheBySymbolById, ArrayCacheByTimestamp
from ccxt.base.errors import ExchangeError, NotSupported
from ccxt.base.errors import AuthenticationError
from ccxt.base.errors import RateLimitExceeded
import time
import hmac


class bybitinverse(bybit):

    def describe(self):
        return self.deep_extend(super(bybitinverse, self).describe(), {
            'id': 'bybitinverse',
            'name': 'ByBit Inverse',
            'urls': {
                'test': {
                    'ws': 'wss://stream-testnet.bybit.com/realtime',
                },
                'api': {
                    'ws': 'wss://stream.bybit.com/realtime',
                },
            },
            'options': {
                'defaultType': 'inverse'
            }
        })
