# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
from ccxtold.async_support import bybit


class bybitlinear(bybit):

    # These are the same as the defaults on bybit.py, but are hardcoded again in case those defaults change
    def describe(self):
        return self.deep_extend(super(bybitlinear, self).describe(), {
            'id': 'bybitlinear',
            'name': 'ByBit Linear',
            'urls': {
                'test': {
                    'ws': 'wss://stream-testnet.bybit.com/realtime_private',
                },
                'api': {
                    'ws': 'wss://stream.bybit.com/realtime_private',
                },
            },
            'options': {
                'defaultType': 'linear'
            }
        })
