# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
from ccxtold.async_support import bybit


class bybitinverse(bybit):

    def describe(self):
        return self.deep_extend(super(bybitinverse, self).describe(), {
            'id': 'bybitinverse',
            'name': 'ByBit Inverse',
            'urls': {
                'test': {
                    'ws': 'wss://stream-testnet.bybit.com/realtime',
                },
                'api': {
                    'ws': 'wss://stream.bybit.com/realtime',
                },
            },
            'options': {
                'defaultType': 'inverse'
            }
        })
